CREATE DATABASE InLock_Games_Manha;
GO

USE InLock_Games_Manha;
GO


CREATE TABLE Estudio
(
	IdEstudio INT PRIMARY KEY IDENTITY
	,NomeEstudio VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE TiposUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY
	,Titulo VARCHAR(255) UNIQUE NOT NULL
);
GO


CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY
	,Email VARCHAR(255) NOT NULL UNIQUE
	,Senha VARCHAR(255) NOT NULL
	,IdTipoUsuario INT FOREIGN KEY REFERENCES TiposUsuario (IdTipoUsuario)
);
GO

CREATE TABLE Jogos
(
	IdJogo INT PRIMARY KEY IDENTITY
	,NomeJogo VARCHAR(200) UNIQUE NOT NULL
	,Descricao VARCHAR(200) NOT NULL
	,DataLancamento DATE
	,Valor FLOAT
	,IdEstudio INT FOREIGN KEY REFERENCES Estudio (IdEstudio)
);
GO
